### ISSUE TITLE
Client Fails with LostRemote in 0.5.2

### ISSUE THREAD

**Issue by JohnLunzer** [0rpc/zerorpc-python#128]
Just as the title states and the tracebacks support. After attempting to connect to the server via zClient.registerClient() I'm timing out. Additionally my server will not take any new clients after the time out. 

This same issue does not occur in 0.4.4, from which I upgraded. I did a fresh install of Anaconda as well. Zerorpc was installed with pip install --no-deps so gevent/greenlet/pyzmq weren't installed over Anaconda's installations. Downgrading to 0.4.4 from 0.5.2 made the problem disappear.

Any help would be appreciated. All necessary details below.

Library Versions:
```
anaconda                  2.3.0                np19py27_0
gevent                    1.0.1                    py27_0
greenlet                  0.4.9                    py27_0
python                    2.7.10                        1
pyzmq                     14.7.0                   py27_0
zeromq                    4.0.5                         0  
zerorpc                   0.5.2                     <pip>
```
Client Side Traceback:
```
07:29:53:root:DEBUG:connected to tcp://10.36.162.1:4243 (status=None)
07:29:53:Client:INFO:G Client started C0
07:29:53:Client:INFO:Kicking off _runClient loop
07:29:53:root:DEBUG:--> new channel dd61696d-e828-47a1-94cc-6533914253d9
07:30:08:Client:CRITICAL:Unable to communicate with server, exiting...
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/tortoise/Software/Tools/stopGap/gClient.py", line 71, in startClientService
    self._runClient()
  File "/tortoise/Software/Tools/stopGap/gClient.py", line 82, in _runClient
    self.zClient.registerClient(self.name)
  File "/anaconda/lib/python2.7/site-packages/zerorpc/core.py", line 257, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/anaconda/lib/python2.7/site-packages/zerorpc/core.py", line 249, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/anaconda/lib/python2.7/site-packages/zerorpc/core.py", line 223, in _process_response
    reply_event = bufchan.recv(timeout=timeout)
  File "/anaconda/lib/python2.7/site-packages/zerorpc/channel.py", line 253, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/anaconda/lib/python2.7/site-packages/gevent/queue.py", line 200, in get
    result = waiter.get()
  File "/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()
  File "/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LostRemote: Lost remote after 10s heartbeat
<Greenlet at 0x7f102d548870: <bound method GClient.startClientService of <gClient.Client object at 0x7f102dbc57d0>>> failed with LostRemote
```
Server Side Traceback when attempting a KeyboardInterrupt:
```
07:29:50:gServer:INFO:G Server started
07:29:50:root:DEBUG:bound to tcp://10.36.162.1:4243 (status=None)
07:29:53:root:DEBUG:<-- new channel dd61696d-e828-47a1-94cc-6533914253d9
07:29:53:clientManager:DEBUG:New client registered C0
^CException in thread Thread-2:
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/anaconda/lib/python2.7/site-packages/zmq/utils/garbage.py", line 47, in run
    msg = s.recv()
  File "zmq/backend/cython/socket.pyx", line 676, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6507)
  File "zmq/backend/cython/socket.pyx", line 710, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6307)
  File "zmq/backend/cython/socket.pyx", line 147, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1877)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6758)
    PyErr_CheckSignals()
KeyboardInterrupt

^CException in thread Thread-4:
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/anaconda/lib/python2.7/site-packages/zmq/utils/garbage.py", line 47, in run
    msg = s.recv()
  File "zmq/backend/cython/socket.pyx", line 676, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6507)
  File "zmq/backend/cython/socket.pyx", line 710, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6307)
  File "zmq/backend/cython/socket.pyx", line 147, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1877)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6758)
    PyErr_CheckSignals()
KeyboardInterrupt

07:32:52:root:DEBUG:-x- closed channel dd61696d-e828-47a1-94cc-6533914253d9
07:32:52:zerorpc.channel:WARNING:zerorpc.ChannelMultiplexer, unable to route event: <"\x00'\x9b\xa9\xd2"> _zpc_hb {'response_to': 'dd61696d-e828-47a1-94cc-6533914253d9', 'message_id': 'dd61696e-e828-47a1-94cc-6533914253d9', 'v': 3} [...]
07:32:52:zerorpc.channel:WARNING:zerorpc.ChannelMultiplexer, unable to route event: <"\x00'\x9b\xa9\xd2"> _zpc_hb {'response_to': 'dd61696d-e828-47a1-94cc-6533914253d9', 'message_id': 'dd61696f-e828-47a1-94cc-6533914253d9', 'v': 3} [...]
^CKeyboardInterrupt
07:37:41:gServer:INFO:G Server received shutdown
```

**Comment by bombela** [comment]
I see that the channel was properly opened. And you are saying that the server becomes unresponsive after the first call. I also see some messages about threads. You are probably blocking the main thread (the one running gevent) in some way or another in your server preventing the gevent main loop to run again and schedule other coroutines, like the one managing the heartbeat.

**Comment by JohnLunzer** [comment]
I will check it out. To help me hone in on what's going on, can you remember any changes made between 0.4.4 and 0.5.2 that would have caused my code to stop working? There were no changes to my code, only the library was upgraded.

**Comment by bombela** [comment]
Sorry for the delay, I couldn't figure out what could be your problem. Maybe with [git bisect](https://git-scm.com/docs/git-bisect) you could find the specific commit that broke your code.
