### ISSUE TITLE
Zerorpc errors/hangs when used in gevent environment AND pyzmq > 13.0.2

### ISSUE THREAD

**Issue by pigmej** [0rpc/zerorpc-python#137]
Install recent gevent and recent pyzmq (15.x let's say).

```
from gevent import monkey
monkey.patch_all()


import zmq.green as zmq
import zerorpc

class Blah(object):

    def blah(self):
        return "foo bar"


s = zerorpc.Server(Blah())
s.bind("tcp://0.0.0.0:1234")
s.run()
```

Run this file, then `zerorpc --client --connect tcp://localhost:1234 blah` and it will hang "forever", but when you stop server, you will receive the message.

Also when you try to stop the server then you will see errors like that:
```
^CException in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/zmq/utils/garbage.py", line 47, in run
    msg = s.recv()
  File "zmq/backend/cython/socket.pyx", line 674, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6971)
  File "zmq/backend/cython/socket.pyx", line 708, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6763)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1931)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7222)
    PyErr_CheckSignals()
KeyboardInterrupt

^CException in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/zmq/utils/garbage.py", line 47, in run
    msg = s.recv()
  File "zmq/backend/cython/socket.pyx", line 674, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6971)
  File "zmq/backend/cython/socket.pyx", line 708, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6763)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1931)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7222)
    PyErr_CheckSignals()
KeyboardInterrupt

^CKeyboardInterrupt
Traceback (most recent call last):
  File "cooler.py", line 13, in <module>
    s.run()
  File "/usr/local/lib/python2.7/dist-packages/zerorpc/core.py", line 172, in run
    self._acceptor_task.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 451, in get
    result = self.parent.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 602, in switch
    return greenlet.switch(self)
KeyboardInterrupt
```

When you comment out first 2 lines (which is gevent monkey patch) everything will work fine.

The failure is obviously related to some issue in gevent_zmq code (bundled with zerorpc-python).

The "solution" is rather simple. Just add 
```
import zmq.green as zmq
import sys
sys.modules['zmq'] = zmq
```

after monkey patch into test file and zerorpc will work again. So the final working file looks like:
```
from gevent import monkey
monkey.patch_all()

import zmq.green as zmq
import sys
sys.modules['zmq'] = zmq


import zerorpc


class Blah(object):

    def blah(self):
        return "foo bar"

s = zerorpc.Server(Blah())
s.bind("tcp://0.0.0.0:1234")
s.run()
```

**Comment by bombela** [comment]
let me know if #136 helps you. This problem has nothing to do with zerorpc. Its a bad interaction between geven.monkey_patch and pyzmq.
