### ISSUE TITLE
Unable to import 'gevent_zmq'

### ISSUE THREAD

**Issue by mikroskeem** [0rpc/zerorpc-python#141]
```
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zerorpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/zerorpc/__init__.py", line 29, in <module>
    from .context import *
  File "/usr/lib/python3.5/site-packages/zerorpc/context.py", line 29, in <module>
    import gevent_zmq as zmq
ImportError: No module named 'gevent_zmq'
```
Arch Linux, zerorpc was installed with `pip install zerorpc`

**Comment by bombela** [comment]
The currently published version on pypi is not compatible with `Python 3`.
You can try the `Python 3` branch from the repo.

**Comment by mikroskeem** [comment]
It works, thank you!
