### ISSUE TITLE
zerorpc.exceptions.LostRemote: Lost remote after 10s heartbeat

### ISSUE THREAD

**Issue by ligangbin117** [0rpc/zerorpc-python#149]
```
[root@node46 zerorpc]# cat server.py 
import zerorpc

class HelloRPC(object):
    def hello(self, name):
        return "Hello, %s" % name

    def add(self, a, b):
        return a + b

s = zerorpc.Server(HelloRPC())
s.bind("tcp://0.0.0.0:4242")
s.run()

[root@node46 zerorpc]# python server.py 
No handlers could be found for logger "zerorpc.channel"
^CKeyboardInterrupt
Traceback (most recent call last):
  File "server.py", line 12, in <module>
    s.run()
  File "/usr/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg/zerorpc/core.py", line 171, in run
    self._acceptor_task.get()
  File "/usr/lib/python2.7/site-packages/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 463, in get
    result = self.parent.switch()
  File "/usr/lib/python2.7/site-packages/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
KeyboardInterrupt


[root@node46 zerorpc]# cat client.py 
import zerorpc

c = zerorpc.Client()
c.connect("tcp://127.0.0.1:4242")
print c.hello("RPC")
print c.add(3, 5)

[root@node46 zerorpc]# python client.py 
Traceback (most recent call last):
  File "client.py", line 5, in <module>
    print c.hello("RPC")
  File "/usr/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg/zerorpc/core.py", line 256, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/usr/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg/zerorpc/core.py", line 248, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/usr/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg/zerorpc/core.py", line 222, in _process_response
    reply_event = bufchan.recv(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg/zerorpc/channel.py", line 255, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/queue.py", line 284, in get
    return self.__get_or_peek(self._get, block, timeout)
  File "/usr/lib/python2.7/site-packages/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/queue.py", line 261, in __get_or_peek
    result = waiter.get()
  File "/usr/lib/python2.7/site-packages/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/usr/lib/python2.7/site-packages/gevent-1.1.2-py2.7-linux-x86_64.egg/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
zerorpc.exceptions.LostRemote: Lost remote after 10s heartbeat



[root@node46 zerorpc]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core

[root@node46 zerorpc]# rpm -qa | grep zero
zeromq-4.1.4-5.el7.x86_64
zeromq-devel-4.1.4-5.el7.x86_64
[root@node46 zerorpc]# python -c "import gevent; print gevent.__version__"
1.1.2

Installed /usr/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg
Processing dependencies for zerorpc==0.5.2
Searching for pyzmq==15.4.0
Best match: pyzmq 15.4.0
Processing pyzmq-15.4.0-py2.7-linux-x86_64.egg
pyzmq 15.4.0 is already the active version in easy-install.pth

Using /usr/lib/python2.7/site-packages/pyzmq-15.4.0-py2.7-linux-x86_64.egg
Searching for msgpack-python==0.4.8
Best match: msgpack-python 0.4.8
Processing msgpack_python-0.4.8-py2.7-linux-x86_64.egg
msgpack-python 0.4.8 is already the active version in easy-install.pth

Using /usr/lib/python2.7/site-packages/msgpack_python-0.4.8-py2.7-linux-x86_64.egg
Searching for gevent==1.1.2
Best match: gevent 1.1.2
Processing gevent-1.1.2-py2.7-linux-x86_64.egg
gevent 1.1.2 is already the active version in easy-install.pth

Using /usr/lib/python2.7/site-packages/gevent-1.1.2-py2.7-linux-x86_64.egg
Searching for greenlet==0.4.10
Best match: greenlet 0.4.10
Processing greenlet-0.4.10-py2.7-linux-x86_64.egg
greenlet 0.4.10 is already the active version in easy-install.pth

Using /usr/lib/python2.7/site-packages/greenlet-0.4.10-py2.7-linux-x86_64.egg

```

could you help me fix this?

**Comment by bombela** [comment]
The server must be running for the client to be able to connect to it...

**Comment by eykjs** [comment]
Got the same issue and my node server is definitly running and is running at the same TCP address
