### ISSUE TITLE
Serialize error on error

### ISSUE THREAD

**Issue by magnusbj** [0rpc/zerorpc-python#154]
Hi, thanks for a great tool
I use zerorpc to communicate between node and python.
In my python code, I raise errors to return unfinished work to node
When python errors occur, I get another error from zerorpc:
```

 4324ERROR:zerorpc.core:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/zerorpc/core.py", line 149, in _async_task
functor.pattern.process_call(self._context, bufchan, event, functor)
File "/usr/local/lib/python2.7/site-packages/zerorpc/patterns.py", line 34, in process_call
channel.emit_event(rep_event)
File "/usr/local/lib/python2.7/site-packages/zerorpc/channel.py", line 235, in emit_event
self._channel.emit_event(event)
File "/usr/local/lib/python2.7/site-packages/zerorpc/heartbeat.py", line 116, in emit_event
self._channel.emit_event(event, timeout)
File "/usr/local/lib/python2.7/site-packages/zerorpc/channel.py", line 155, in emit_event
self._multiplexer.emit_event(event, timeout)
File "/usr/local/lib/python2.7/site-packages/zerorpc/channel.py", line 67, in emit_event
return self._events.emit_event(event, timeout)
File "/usr/local/lib/python2.7/site-packages/zerorpc/events.py", line 323, in emit_event
parts.extend(['', event.pack()])
File "/usr/local/lib/python2.7/site-packages/zerorpc/events.py", line 192, in pack
return msgpack.Packer().pack((self._header, self._name, self._args))
File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
File "msgpack/_packer.pyx", line 221, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3230)
File "msgpack/_packer.pyx", line 221, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3230)
File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)
TypeError: can't serialize AssertionError('My error description)
```

I run zerorpc from the python app with:

```
s = zerorpc.Server(Densities())
s.bind("tcp://0.0.0.0:5000")
s.run()
print 'zerorpc connected'
```
And the flow is going through Docker.
For normal returns everything is good.

What am I doing wrong?

**Comment by bombela** [comment]
I suspect you are trying to return the exception instead letting bubble for zerorpc to catch.

This works:
```python
def foo():
  assert 1 == 2
```

This will not work:
```python
def foo():
  try:
      assert 1 == 2
  except Exception as e:
      return e
```

**Comment by magnusbj** [comment]
Thanks!
