### ISSUE TITLE
Server.stop() triggers gevent.hub.BlockingSwitchOutError

### ISSUE THREAD

**Issue by daemotron** [0rpc/zerorpc-python#164]
When implementing a backend based on ZeroRPC, I noticed that implementing a signal handler catching SIGINT and then gracefully shutting down the server triggers a BlockingSwitchOutError.

```
Traceback (most recent call last):
  File "server.py", line 19, in handle_sigint
    Server.close()
  File "virtualenv/test/lib/python3.6/site-packages/zerorpc/core.py", line 295, in close
    ServerBase.close(self)
  File "virtualenv/test/lib/python3.6/site-packages/zerorpc/core.py", line 92, in close
    self.stop()
  File "virtualenv/test/lib/python3.6/site-packages/zerorpc/core.py", line 183, in stop
    self._acceptor_task.kill()
  File "virtualenv/test/lib/python3.6/site-packages/gevent/greenlet.py", line 441, in kill
    waiter.get()
  File "virtualenv/test/lib/python3.6/site-packages/gevent/hub.py", line 899, in get
    return self.hub.switch()
  File "virtualenv/test/lib/python3.6/site-packages/gevent/hub.py", line 629, in switch
    switch_out()
  File "virtualenv/test/lib/python3.6/site-packages/gevent/hub.py", line 633, in switch_out
    raise BlockingSwitchOutError('Impossible to call blocking function in the event loop callback')
gevent.hub.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
Sat May 27 08:34:46 2017
Traceback (most recent call last):
  File "server.py", line 34, in <module>
    main()
  File "server.py", line 31, in main
    Server.run()
  File "virtualenv/test/lib/python3.6/site-packages/zerorpc/core.py", line 176, in run
    self._acceptor_task.get()
  File "virtualenv/test/lib/python3.6/site-packages/gevent/greenlet.py", line 465, in get
    result = self.parent.switch()
  File "virtualenv/test/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
```

My sample code to reproduce the issue can be found here:
https://gist.github.com/daemotron/ec2b58011fa2f008178a1e2c5a331cd5

I'm not 100% I'm using the ZeroRPC Server() implementation correctly; as it's mostly undocumented I just sticked with what I understood from looking at the code.

Environment:
* Python 3.6.1
* macOS Sierra (10.12.3)
* Python package versions:
  * gevent==1.2.1
  * greenlet==0.4.12
  * zerorpc==0.6.1

**Comment by bombela** [comment]
You are indirectly trying to manipulate coroutine(s) from a signal handler.
Outside of gevent's control. For a cooperative version, take a look at:
http://www.gevent.org/gevent.signal.html

**Comment by daemotron** [comment]
Indeed, you're right &ndash; using `gevent.signal()` instead of `signal.signal()` prevents the exception from occurring. Thanks for the hint!
