### ISSUE TITLE
Using Exceptions in Python (server) fails

### ISSUE THREAD

**Issue by mrlarssen** [0rpc/zerorpc-python#167]
I have a node client and a python server, and when trying to raise an Exception in Python, I get the following error:

```
Mon Jun 26 11:24:13 2017 <Greenlet at 0x7ff6b8da6af0: <bound method Server._async_task of <zerorpc.core.Server object at 0x7ff6b901ec10>>(<zerorpc.events.Event object at 0x7ff6b8da9690>)> failed with BaseException
python_1   | 
python_1   | WARNING:zerorpc.channel:zerorpc.ChannelMultiplexer, unable to route event: <'\x00k\x8bEl'> _zpc_hb {u'response_to': u'6f2baa6b-8304-4bea-a2ee-000000000000', u'message_id': u'6f2baa6b-8304-4bea-a2ee-000000000001', u'v': 3} [...]


node_1     | An error occurred: { HeartbeatError: Lost remote after 10000ms
node_1     |     at Error (native)
node_1     |     at Object.createErrorResponse (/code/node_modules/zerorpc/lib/util.js:53:10)
node_1     |     at ClientChannel.<anonymous> (/code/node_modules/zerorpc/lib/client.js:147:26)
node_1     |     at emitOne (events.js:96:13)
node_1     |     at ClientChannel.emit (events.js:188:7)
node_1     |     at Timeout._repeat (/code/node_modules/zerorpc/lib/channel.js:198:18)
node_1     |     at Timeout.wrapper [as _onTimeout] (timers.js:421:11)
node_1     |     at tryOnTimeout (timers.js:228:11)
node_1     |     at Timer.listOnTimeout (timers.js:202:5) name: 'HeartbeatError' } 
```

I have seen a previous issue, where a similar error si being addressed. However, the suggested solution seemed to be to use "assert". Asserts are strictly for development purposes, and using Exceptions are therefore preferred (read: needed). 

Node (client):
```
client.invoke("invoke_exception", function (error, result, more) {
        console.error("An error occurred:", error);
 })
```

Python (server):
``
 def invoke_exception(self):
        raise Exception("SOME ERROR")
```

Any suggestions as to how to deal with Exceptions in Python?

**Comment by bombela** [comment]
zerorpc is effectively supposed to convert exception into a zerorpc error. Which should then be sent back to the client. Not sure what is going on here. Is it working with a Python client against a Python server?

**Comment by mrlarssen** [comment]
Thank you for your response.

Invoking the same function from a Python Client results in the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/zerorpc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/zerorpc/cli.py", line 308, in main
    return run_client(args)
  File "/usr/local/lib/python2.7/site-packages/zerorpc/cli.py", line 267, in run_client
    results = client(args.command, *call_args)
  File "/usr/local/lib/python2.7/site-packages/zerorpc/core.py", line 270, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/usr/local/lib/python2.7/site-packages/zerorpc/core.py", line 238, in _process_response
    reply_event, self._handle_remote_error)
  File "/usr/local/lib/python2.7/site-packages/zerorpc/patterns.py", line 45, in process_answer
    raise exception
zerorpc.exceptions.RemoteError: Traceback (most recent call last):
Exception: SOME ERROR
```

Looks like this is the expected behavior? I assume the error is with node then?

**Comment by bombela** [comment]
Effectively, you did get an exception RemoteError from the zerorpc client. Which encapsulates information about the remote error, ...obviously.

I will try to find some time to debug this. Sorry for the trouble.

**Comment by mrlarssen** [comment]
Thank you.

I added:

```
client.on("error", function(error) {
    console.error("RPC client error:", error);
});
```

which now gives me the following result:

```
python_1        | ERROR:zerorpc.core:
python_1        | Traceback (most recent call last):
python_1        | Exception: SOME ERROR
node_1           | An error occurred: { Traceback (most recent call last):
node_1           | Exception: SOME ERROR
node_1           |  name: <Buffer 45 78 63 65 70 74 69 6f 6e> }
```

**Comment by bombela** [comment]
Right, it does seem to be a really awkward way to catch errors though. Will try to look into it.

**Comment by chiaramdelucia** [comment]
@bombela, I executed the `client.on('error', ())` function as written in the README.md file, but I'm still unable to catch the exception like @mrlarssen can. I'm using this [fork](https://github.com/0rpc/zerorpc-node/pull/84) and wondering if you know this issue is related to using zeromq insteaad of zmq and msgpack-lite instead of msgpack.

Thank you for any insight you could provide.
