### ISSUE TITLE
ERROR:zerorpc.core:

### ISSUE THREAD

**Issue by yonasayanaw** [0rpc/zerorpc-python#168]
![image](https://user-images.githubusercontent.com/16515161/27850712-4aa29640-610b-11e7-9050-5485d7fff0bb.png)

INFO:root:Starting rpc Server
INFO:root:Adding new SLA to the System ID: 12011

parties:
    
    Rafael
        roles: consumer 
    
    Imt
        roles: provider 

term groups:

    Small_VM
        Imt -> Rafael:cCpu in [1,2] #
        Imt -> Rafael:ram in [1,1] #

    Centralized_VM
        Imt -> Rafael:cCpu in [2,4] #
        Imt -> Rafael:ram in [8,16] #

    Cluster
        Imt -> Rafael:RT_delay in [0.0, 0.6] ms
        [2,2] of Small_VM

terms:
    [1,1] of Cluster
    Imt -> Rafael:interface has {OCCI,UCI} or {EC2}
    Imt -> Rafael:replication is true

guarantees:

   on violation of Cluster :

        if Cluster<1 then
            notify
            renegotiate

   on violation of RT_delay :

        if RT_delay>0.6 then
            notify

```
ERROR:zerorpc.core:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\zerorpc\core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "C:\Python27\lib\site-packages\zerorpc\patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "C:\Python27\lib\site-packages\zerorpc\decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "C:\Users\yonas\Desktop\New\slac-language\SLAC\SLAC\Communication_Interfaces\PMS.py", line 11, in add_sla
    return self.framework.add_single_SLA_network( sla )
  File "framework.py", line 123, in add_single_SLA_network
    sla = Z3.SLA_Constraint.SLA_to_Constraint(**parsed_SLA[0])
  File "C:\Users\yonas\Desktop\New\slac-language\SLAC\SLAC\Z3\SLA_Constraint.py", line 16, in __init__
    self.solver_SLA = Solver()
NameError: global name 'Solver' is not defined
```

Hello friends I have tried to run this program many times, but i experienced such problems.  Please help me how to solve this problem. thank you!

**Comment by bombela** [comment]
You have an undefined name: `'Solver' is not defined`. It is not related to zerorpc.
