### ISSUE TITLE
Sockets are left open until Python terminates if the TCP connection never occurs

### ISSUE THREAD

**Issue by matthewbalvanz-wf** [0rpc/zerorpc-python#169]
I'm attempting to use a client from zerorpc 0.6.1 inside a long running application (a web server) and have discovered that sockets are sometimes left open forever. I was able to reproduce the issue using the Python REPL by attempting to connect to a server that does not exist:

```python
>>> import zerorpc
>>> client = zerorpc.Client('tcp://10.254.254.1:9999')
>>> client.echo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matthewbalvanz/envs/web/lib/python2.7/site-packages/zerorpc/core.py", line 278, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/Users/matthewbalvanz/envs/web/lib/python2.7/site-packages/zerorpc/core.py", line 270, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/Users/matthewbalvanz/envs/web/lib/python2.7/site-packages/zerorpc/core.py", line 227, in _process_response
    reply_event = bufchan.recv(timeout=timeout)
  File "/Users/matthewbalvanz/envs/web/lib/python2.7/site-packages/zerorpc/channel.py", line 255, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/Users/matthewbalvanz/envs/web/lib/python2.7/site-packages/gevent/queue.py", line 283, in get
    return self.__get_or_peek(self._get, block, timeout)
  File "/Users/matthewbalvanz/envs/web/lib/python2.7/site-packages/gevent/queue.py", line 260, in __get_or_peek
    result = waiter.get()
  File "/Users/matthewbalvanz/envs/web/lib/python2.7/site-packages/gevent/hub.py", line 898, in get
    return self.hub.switch()
  File "/Users/matthewbalvanz/envs/web/lib/python2.7/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
zerorpc.exceptions.LostRemote: Lost remote after 10s heartbeat
```
Then checking my machine's open ports I see it in SYN_SENT status:
```
$ netstat -aln | grep "10.254.254.1.9999"
tcp4       0      0  10.50.10.53.64279      10.254.254.1.9999         SYN_SENT   
```
I've attempted to call `client.close()` the close method on the internally referenced socket, and `del client` to try to get garbage collection to shut it down, but it remains until I exit Python. When deployed it isn't immediately a problem, but eventually the application encounters enough network inconsistency that it runs out of open file handles and can no longer open new connections.

Is there another way to close the socket that I've missed?

**Comment by bombela** [comment]
hello, sorry for the inconvenience. I am extremely busy right now. For what you describe, this is a serious bug, and I intend to look into it in the weeks to come. client.close() should definitively close the zmq socket, which in turn should close any system socket.

Please not that if you always connect to a known, fixed set of servers. You can simply keep the client around, instead of creating a new one every time you need to send a msg. This is usually how people use zerorpc, and might explain why this socket leak wasn't reported before.

Btw, you cannot use zerorpc withing the python interpreter, because you are outside of the gevent ioloop.  You will often get a lostremote from the interpreter. If your request/response roundtrip is faster than the heartbeat, I believe it somewhat works.
