### ISSUE TITLE
ord() expected string of length 1, but memoryview found

### ISSUE THREAD

**Issue by sleighsoft** [0rpc/zerorpc-python#176]
I am trying out the python hello world example from the front page. I connect with the cli command once the server started.

Miniconda (installed zerorpc with pip)
Python 3.6.2
Windows 10

Packages:
```
bleach==1.5.0
certifi==2016.2.28
future==0.16.0
gevent==1.2.2
greenlet==0.4.12
html5lib==0.9999999
Markdown==2.6.9
msgpack-python==0.4.8
numpy==1.13.1
protobuf==3.4.0
pygame==1.9.3
pyzmq==16.0.2
six==1.11.0
tensorflow==1.3.0
tensorflow-tensorboard==0.1.6
Werkzeug==0.12.2
wincertstore==0.2
zerorpc==0.6.1
```

Traceback:
```
zerorpc.ChannelMultiplexer ignoring error on recv
Traceback (most recent call last):
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\channel.py", line 78, in _channel_dispatcher
    event = self._events.recv()
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\events.py", line 365, in recv
    event = Event.unpack(get_pyzmq_frame_buffer(blob))
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\events.py", line 215, in unpack
    unpacked_msg = unpacker.unpack()
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\msgpack\fallback.py", line 570, in unpack
    ret = self._fb_unpack(EX_CONSTRUCT, write_bytes)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\msgpack\fallback.py", line 498, in _fb_unpack
    typ, n, obj = self._read_header(execute, write_bytes)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\msgpack\fallback.py", line 347, in _read_header
    b = ord(c)
TypeError: ord() expected string of length 1, but memoryview found
```

**Comment by bombela** [comment]
Hello,

This is because msgpack is falling back on a pure python implementation
instead of compiling a more optimized version. And for some reason the fall
back cannot handle a memory view as argument.

zerorpc should ultimately be able to work with the fallback. By detecting
it and converting the memory view to a buffer (slow but hey it's a
fallback). But I have never managed to reproduce the error on my system. (I
am on Linux).

You can try 'pip install --reinstall msgpack' and see if you can get it to
build.

Best,
fx

**Comment by sleighsoft** [comment]
That does not fix the problem.
I can convert the memoryview to a bytes object at at the places where it fails to call a method on the memoryview but I run into the following problem later in the code
```
Traceback (most recent call last):
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\gevent\greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\core.py", line 163, in _async_task
    bufchan.emit_event(reply_event)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\channel.py", line 234, in emit_event
    self._channel.emit_event(event)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\heartbeat.py", line 116, in emit_event
    self._channel.emit_event(event, timeout)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\channel.py", line 154, in emit_event
    self._multiplexer.emit_event(event, timeout)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\channel.py", line 66, in emit_event
    return self._events.emit_event(event, timeout)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\events.py", line 347, in emit_event
    parts.extend([b'', event.pack()])
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\zerorpc\events.py", line 208, in pack
    r = msgpack.Packer(use_bin_type=True).pack(payload)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\msgpack\fallback.py", line 741, in pack
    self._pack(obj)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\msgpack\fallback.py", line 729, in _pack
    self._pack(obj[i], nest_limit - 1)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\msgpack\fallback.py", line 733, in _pack
    nest_limit - 1)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\msgpack\fallback.py", line 831, in _fb_pack_map_pairs
    self._pack(v, nest_limit - 1)
  File "C:\Development\Tools\miniconda\envs\tf-backbone\lib\site-packages\msgpack\fallback.py", line 738, in _pack
    raise TypeError("Cannot serialize %r" % obj)
TypeError: Cannot serialize <memory at 0x000001A2BAC0B588>
Thu Oct 19 09:58:46 2017 <Greenlet at 0x1a2babd69c8: <bound method ServerBase._async_task of <zerorpc.core.Server object at 0x000001A2BA5FA208>>(<zerorpc.events.Event object at 0x000001A2BADA4360)> failed with TypeError
```

**Comment by bombela** [comment]
I think this was ultimately fixed.
