### ISSUE TITLE
Invalid argument error when trying example 

### ISSUE THREAD

**Issue by mentaal** [0rpc/zerorpc-python#188]
Hi, when I try the command line examples, I get the following error:

(zerorpc_venv) C:\Users\gkuhn\python_envs>zerorpc tcp://127.0.0.1://1234
connecting to "tcp://127.0.0.1://1234"
Traceback (most recent call last):
  File "C:\Users\gkuhn\python_envs\zerorpc_venv\Scripts\zerorpc-script.py", line 11, in <module>
    load_entry_point('zerorpc==0.6.1', 'console_scripts', 'zerorpc')()
  File "c:\users\gkuhn\python_envs\zerorpc_venv\lib\site-packages\zerorpc\cli.py", line 310, in main
    return run_client(args)
  File "c:\users\gkuhn\python_envs\zerorpc_venv\lib\site-packages\zerorpc\cli.py", line 244, in run_client
    setup_links(args, client)
  File "c:\users\gkuhn\python_envs\zerorpc_venv\lib\site-packages\zerorpc\cli.py", line 104, in setup_links
    socket.connect(endpoint)
  File "c:\users\gkuhn\python_envs\zerorpc_venv\lib\site-packages\zerorpc\socket.py", line 40, in connect
    return self._events.connect(endpoint, resolve)
  File "c:\users\gkuhn\python_envs\zerorpc_venv\lib\site-packages\zerorpc\events.py", line 318, in connect
    r.append(self._socket.connect(endpoint_))
  File "c:\users\gkuhn\python_envs\zerorpc_venv\lib\site-packages\zerorpc\gevent_zmq.py", line 105, in connect
    return super(Socket, self).connect(*args, **kwargs)
  File "zmq\backend\cython\socket.pyx", line 580, in zmq.backend.cython.socket.Socket.connect
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument

Environment:
(zerorpc_venv) C:\Users\gkuhn\python_envs>pip freeze
future==0.16.0
gevent==1.3a2
greenlet==0.4.13
msgpack-python==0.5.5
pyzmq==17.0.0
zerorpc==0.6.1

**Comment by rtobar** [comment]
Looks like the endpoint is not well defined. You are using` tcp://127.0.0.1://1234`. Try with `tcp://127.0.0.1:1234`

**Comment by mentaal** [comment]
Wow....that's embarrassing!
