### ISSUE TITLE
How to disambiguate a "connect" method?

### ISSUE THREAD

**Issue by acburigo** [0rpc/zerorpc-python#191]
Here is a modified version of the RPC example in ZeroRPC website:

Server:
```
import zerorpc

class HelloRPC(object):
    def connect(self, name):
        return "Connected to %s" % name

s = zerorpc.Server(HelloRPC())
s.bind("tcp://0.0.0.0:4242")
s.run()
```

Client:
```
import zerorpc

c = zerorpc.Client()
c.connect("tcp://127.0.0.1:4242")
print(c.connect("RPC")) # ???
```

How can the client call the server's `HelloRPC.connect` method?

**Comment by bombela** [comment]
c("connect", "RPC")

**Comment by acburigo** [comment]
Here's my output when using your suggestion:

Server:
```
ipython
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import zerorpc

In [2]: class HelloRPC(object):
   ...:     def connect(self, name):
   ...:         return "Connected to %s" % name
   ...:

In [3]: s = zerorpc.Server(HelloRPC())

In [4]: s.bind("tcp://0.0.0.0:4242")
Out[4]: [None]

In [5]: s.run()

Traceback (most recent call last):
  File "c:\users\arthu\appdata\local\programs\python\python36\lib\site-packages\zerorpc\core.py", line 152, in _async_task
    raise NameError(event.name)
NameError: connect
```

Client:
```
ipython
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import zerorpc

In [2]: c = zerorpc.Client()

In [3]: c.connect("tcp://127.0.0.1:4242")
Out[3]: [None]

In [4]: print(c("connect", "RPC"))
---------------------------------------------------------------------------
RemoteError                               Traceback (most recent call last)
<ipython-input-4-d96bbb149693> in <module>()
----> 1 print(c("connect", "RPC"))

c:\users\arthu\appdata\local\programs\python\python36\lib\site-packages\zerorpc\core.py in __call__(self, method, *args, **kargs)
    268
    269         if kargs.get('async', False) is False:
--> 270             return self._process_response(request_event, bufchan, timeout)
    271
    272         async_result = gevent.event.AsyncResult()

c:\users\arthu\appdata\local\programs\python\python36\lib\site-packages\zerorpc\core.py in _process_response(self, request_event, bufchan, timeout)
    236
    237         return pattern.process_answer(self._context, bufchan, request_event,
--> 238                 reply_event, self._handle_remote_error)
    239
    240     def __call__(self, method, *args, **kargs):

c:\users\arthu\appdata\local\programs\python\python36\lib\site-packages\zerorpc\patterns.py in process_answer(self, context, channel, req_event, rep_event, handle_remote_error)
     43                 exception = handle_remote_error(rep_event)
     44                 context.hook_client_after_request(req_event, rep_event, exception)
---> 45                 raise exception
     46             context.hook_client_after_request(req_event, rep_event)
     47             return rep_event.args[0]

RemoteError: Traceback (most recent call last):
  File "c:\users\arthu\appdata\local\programs\python\python36\lib\site-packages\zerorpc\core.py", line 152, in _async_task
    raise NameError(event.name)
NameError: connect
```

**Comment by charlesRmajor** [comment]
I think you want:
```
c.invoke('connect', 'RPC', (error, result) => {console.log(error); console.log(result)})
```

**Comment by bombela** [comment]
@charlesRmajor your answer is for zerorpc-node, while @acburigo is using zerorpc-python.

The reason you get a `NameError`, is because `connect` is also a reserved method on the server.

When given an object, `zerorpc.Server` filters out methods that conflicts with itself. Since `connect` already exists on `zerorpc.Server` it is ignored from the `HelloRPC` object. Here is the logic if you are curious: [core.py#L75](https://github.com/0rpc/zerorpc-python/blob/master/zerorpc/core.py#L75).

The reason behind this is because unless an object/dict is passed to the `methods` argument of the `zerorpc.Server` constructor, it is assumed that all sub-class methods should be exposed.

The following two examples are identical in behavior:

Composition:

```python
class HelloRPC(object):
    def connect(self, name):
        return "Connected to %s" % name

s = zerorpc.Server(HelloRPC())
s.bind("tcp://0.0.0.0:4242")
s.run()
```

Inheritance:

```python
class HelloRPC(zerorpc.Server):
    def connect(self, name):
        return "Connected to %s" % name

s = HelloRPC()
s.bind("tcp://0.0.0.0:4242")
s.run()
```

There is light at the end of the tunnel though.

When given a dict however, `zerorpc.Server` doesn't filter anything, and any unicode string makes for a valid method name:

```python
class HelloRPC(object):
    def connect(self, name):
        return "Connected to %s" % name

h = HelloRPC()
s = zerorpc.Server({"connect": h.connect})
s.bind("tcp://0.0.0.0:4242")
s.run()
```
