### ISSUE TITLE
<zerorpc.events.Event object at 0x7f1871fe4e10>)> failed with KeyError

### ISSUE THREAD

**Issue by zhangjustin** [0rpc/zerorpc-python#199]
I got follow error on my production environment:
```
Traceback (most recent call last):
  File "/var/rpc/releases/20180808072117/.virtualenv/local/lib64/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/var/rpc/releases/20180808072117/.virtualenv/local/lib/python2.7/site-packages/zerorpc/core.py", line 162, in _async_task
    bufchan.close()
  File "/var/rpc/releases/20180808072117/.virtualenv/local/lib/python2.7/site-packages/zerorpc/channel.py", line 203, in close
    self._channel.close()
  File "/var/rpc/releases/20180808072117/.virtualenv/local/lib/python2.7/site-packages/zerorpc/heartbeat.py", line 70, in close
    self._channel.close()
  File "/var/rpc/releases/20180808072117/.virtualenv/local/lib/python2.7/site-packages/zerorpc/channel.py", line 139, in close
    del self._multiplexer._active_channels[self._channel_id]
KeyError: '5b6aadde2914a'
Wed Aug  8 16:46:22 2018 <Greenlet at 0x7f18700d65f0: <bound method _Server._async_task of <zask.ext.zerorpc._Server object at 0x7f1880ccf910>>(<zerorpc.events.Event object at 0x7f1871fe4e10>)> failed with KeyError
```
with
```
zerorpc (0.5.2)
msgpack-python (0.4.8)
msgpack (0.5.6)
gevent (1.2.2)
pyzmq (13.1.0)
```
It's my production environment  and high load
i can't find this error on my staging environment, only few  people visit staging environment.

### Note
we use zerorpc on framework [zask](https://github.com/juwai/zask)

Thanks,
Justin.

**Comment by bombela** [comment]
Mixing threads and gevent perhaps? This would produce a race condition on the list of opens channels.
