### ISSUE TITLE
Compatibility with transitions library

### ISSUE THREAD

**Issue by rohern** [0rpc/zerorpc-python#200]
ZeroRPC does not play well with the transitions library when creating a ZeroRPC server from an object employing a transitions Machine.

I wrote up an example:

```python
import zerorpc
from transitions import Machine

class Switch(object):
    states = ["on", "off"]

    def __init__(self):
      self.machine = Machine(model=self, states=Switch.states, initial="off")

      self.machine.add_transition(
        "flip", # trigger
        "on", # source
        "off", # destination
        )     
      self.machine.add_transition(
        "flip", # trigger
        "off", # source
        "on", # destination
        )     
    
s = zerorpc.Server(Switch())
s.bind("tcp://0.0.0.0:4242")
s.run()
```

Trying to run this code results in:
```
Traceback (most recent call last):
  File "server.py", line 21, in <module>
    s = zerorpc.Server(Switch())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zerorpc/core.py", line 292, in __init__
    pool_size, heartbeat)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zerorpc/core.py", line 72, in __init__
    self._methods[k] = rep(functor)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zerorpc/decorators.py", line 36, in __init__
    self.__name__ = functor.__name__
AttributeError: 'functools.partial' object has no attribute '__name__'
```

I am looking into a workaround presently, but any help would be appreciated.

**Comment by bombela** [comment]
zerorpc can only expose "common" methods to the network. Here it looks like self.machine dynamically injects method on the Switch class. And they are missing the `__name__` attribute.

It might be possible to improve zerorpc such that the name of the attribute from the class is used instead of the method `__name__` attribute.

Now, it is not necessarily a good practice to expose dynamically created methods over the network. As you might be exposing yourself too much. I would keep my Machine private, and manually implement public methods one by one. It also makes it easy to expose the docstring this way.

**Comment by rohern** [comment]
That's helpful! Thank you.

Here's an example of this for anyone else who might have this issue:

```python
import zerorpc
from transitions import Machine

class Switch(Machine):
  def __init__(self):
    states = ["on", "off"]
    Machine.__init__(self, states=states, initial="off")

    self.add_transition(
      "flip", # trigger
      "on", # source
      "off", # destination
      )     
    self.add_transition(
      "flip", # trigger
      "off", # source
      "on", # destination
      )     
    
class SwitchServer():
  def __init__(self):
    self._switch = Switch()

  def flip(self):
    self._switch.flip()
    return self._switch.state

s = zerorpc.Server(SwitchServer())
s.bind("tcp://0.0.0.0:4242")
s.run()
```
