### ISSUE TITLE
recreate server object bind fails

### ISSUE THREAD

**Issue by tiagocoutinho** [0rpc/zerorpc-python#208]
## Problem
I am running the following zerorpc server:

```python
import zerorpc
import gevent

def run(server):
    print('started 0RPC server')
    server.run()
    print('finished 0RPC server')

def start():
    global PORT
    bind = "tcp://*:4242"
    server = zerorpc.Server(gevent)
    server.bind(bind)
    task = gevent.spawn(run, server)
    task.server = server
    return task

while True:
    try:
        task = start()
        while True:
            gevent.sleep(1)
    except KeyboardInterrupt:
        print('Stopping...')
        task.server.stop()
        task.join()
```
When I hit Ctrl-C I get the following error:
```
started 0RPC server
^CKeyboardInterrupt
2019-02-12T09:46:46Z
Stopping...
finished 0RPC server
Traceback (most recent call last):
  File "zrpc_test3.py", line 22, in <module>
    task = start()
  File "zrpc_test3.py", line 14, in start
    server.bind(bind)
  File "/usr/lib/python2.7/site-packages/zerorpc/socket.py", line 43, in bind
    return self._events.bind(endpoint, resolve)
  File "/usr/lib/python2.7/site-packages/zerorpc/events.py", line 325, in bind
    r.append(self._socket.bind(endpoint_))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
```
## Expected behaviour

After hitting Ctrl-C the server should restart properly

## Context

I am writting an RPC extension to [supervisor](https://github.com/Supervisor/supervisor) called [multivisor](https://github.com/tiagocoutinho/multivisor). 

When supervisor daemon is asked to restart, multivisor is supposed to restart the ZeroRPC server from scratch. 
The actual scenario is more complex since I need to spawn a dedicated thread to handle ZeroRPC server and communicate with it using [gevent.hub.Watcher](http://www.gevent.org/api/gevent.hub.html#gevent._interfaces.IWatcher). This is because supervisor runs a [asyncore](https://docs.python.org/2/library/asyncore.html) based I/O loop.
The output I see in supervisord after a restart is:
```
...
RPCServer WARNING 2019-02-12 08:38:02,140 MVRPC: noticed that supervisor is dying
2019-02-12 08:38:02,139 INFO waiting for vacuum_OH1 to die
2019-02-12 08:38:02,141 INFO stopped: vacuum_OH1 (terminated by SIGTERM)
2019-02-12 08:38:02,159 INFO RPC interface 'supervisor' initialized
2019-02-12 08:38:02,159 INFO RPC interface 'multivisor' initialized
2019-02-12 08:38:02,159 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2019-02-12 08:38:02,159 INFO supervisord started with pid 29369
RPCServer INFO 2019-02-12 08:38:02,159 MVRPC: 0RPC: spawn server on 29369...
Assertion failed: nbytes == sizeof dummy (src/signaler.cpp:236)
Aborted (core dumped)
```

In trying to reproduce the problem with the server above I came across the problem I explained.
I believe it to be the source of my problems.

If anyone is interested, the multivisor RPC is [here](https://github.com/tiagocoutinho/multivisor/blob/master/multivisor/rpc.py)

Thanks in advance for all the help

**Comment by tiagocoutinho** [comment]
Thanks, it works (of course :-)
