### ISSUE TITLE
zerorpc 0.6.3  AttributeError: 'module' object has no attribute 'Server'

### ISSUE THREAD

**Issue by Paradise2010** [0rpc/zerorpc-python#220]
I can import zerorpc, and confirm Server class was in zerorpc.core module. but the interpreter always report "AttributeError: 'module' object has no attribute 'Server'"
- Test platform:

 windows 10,python 2.7.15
Traceback (most recent call last):
  File "e:/Tool_development/python_resource/py27virenv/testAutomation/zerorpcproject/zerorpc.py", line 7, in <module>
    import zerorpc
  File "e:\Tool_development\python_resource\py27virenv\testAutomation\zerorpcproject\zerorpc.py", line 8, in <module>
    s = zerorpc. Server()
AttributeError: 'module' object has no attribute 'Server'

- Test Script:
class HelloRPC(object):
    def hello(self, name):
        return "Hello, %s" % name

import zerorpc
test = zerorpc.Server(HelloRPC())
s = zerorpc.Server()
s.bind("tcp://0.0.0.0:4242")
s.run()
-  pip list:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package    Version
---------- -------
cffi       1.12.3
future     0.17.1
gevent     1.4.0
greenlet   0.4.15
msgpack    0.6.1
pip        19.1.1
pycparser  2.19
pyzmq      18.0.2
setuptools 41.0.1
wheel      0.33.4
zerorpc    0.6.3

**Comment by ntlind** [comment]
also experiencing this issue. any idea what might be causing this import to fail @bombela ?

**Comment by bombela** [comment]
Are you on MS Windows as well? If you follow the path to the zerorpc module
do you find all the files?

Can you add here the full error. Just in case something obvious comes up.
Try importing other symbols from zerorpc to find out by elimination what is
happening.
