### ISSUE TITLE
Cannot close server using .close() or .stop() or exit(), server keep running in the background

### ISSUE THREAD

**Issue by AlmoGSIntel** [0rpc/zerorpc-python#225]
I am using zeroRPC to comunicate between an electron app and python.
everything is working greate, but I can't manage to close the server after the program is closed.
I currently trying to send an .invoke() command that does ServerName.close().
I tried exit() stop() and nothing happend.
when close() is called after a momment this pops up in the python console but stayes up:
```
Traceback (most recent call last):
  File "X:/Electron/Sorti/SortiServer.py", line 58, in <module>
    sortiMind.run()
  File "X:\Electron\Sorti\SortiPyVenv\lib\site-packages\zerorpc\core.py", line 179, in run
    self._task_pool.join(raise_error=True)
  File "X:\Electron\Sorti\SortiPyVenv\lib\site-packages\gevent\pool.py", line 428, in join
    result = self._empty_event.wait(timeout=timeout)
  File "src/gevent/event.py", line 127, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 192, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
	Hub: <Hub '' at 0x1fcce63ebf0 default default pending=0 ref=0 thread_ident=0x20f0>
	Handles:
[HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FCCBDFAD48>, type=b'check', watcher=<loop at 0x1fcce68caf0 default default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FCCBDDD538>, type=b'timer', watcher=<loop at 0x1fcce68caf0 default default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FCCBDFA668>, type=b'prepare', watcher=<loop at 0x1fcce68caf0 default default pending=0 ref=0>, ref=0, active=1, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FCCBDF9F88>, type=b'check', watcher=<loop at 0x1fcce68caf0 default default pending=0 ref=0>, ref=1, active=0, closing=0),
 HandleState(handle=<cdata 'struct uv_handle_s *' 0x000001FCCBD6C278>, type=b'poll', watcher=None, ref=1, active=0, closing=0)]
```
After 10 seconds in the node.js console this pops up and the server is not responding anymore:
```
Error [HeartbeatError]: Lost remote after 10000ms
    at Object.createErrorResponse (X:\Electron\Sorti\node_modules\zerorpc\lib\util.js:53:10)
    at ClientChannel.<anonymous> (X:\Electron\Sorti\node_modules\zerorpc\lib\client.js:163:26)
    at ClientChannel.emit (events.js:203:13)
    at Timeout._onTimeout (X:\Electron\Sorti\node_modules\zerorpc\lib\channel.js:198:18)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'HeartbeatError'
}
```
My setup is this:
I have two clients connected to the server using the connect command and the server is using the bind command.
one client is used for all the data transections and the other one is only to invoke the close command.
server is :
```
serverName = zerorpc.Server(SortiMind())
serverName .bind("tcp://127.0.0.1:27997")
serverName .run()
```
client one:
```
const zerorpc = require("zerorpc");
const client = new zerorpc.Client();
client.connect("tcp://127.0.0.1:27997");
```

client two:
```
serverName = zerorpc.Server(SortiMind())
serverName .bind("tcp://127.0.0.1:27997")
serverName .run()

```

close command on client:
```
client.invoke("close_program", (error, res, more) => {
                    console.log(error);
                });
```

close command on server(it is one of the class methods):
```
    def close_program(self):
        serverName .close()
```
Please help me.

**Comment by AlmoGSIntel** [comment]
Manage to fix the issue by spawning a child process with the server, when the parent close the child closes as well.

**Comment by AlmoGSIntel** [comment]
Manage to fix the issue by spawning a child process with the server, when the parent close the child closes as well.
