### ISSUE TITLE
module 'collections' has no attribute 'Iterator'

### ISSUE THREAD

**Issue by glyh** [0rpc/zerorpc-python#250]
To reproduce:
```shell
$ zerorpc --server --bind tcp://*:1234 time
$ zerorpc --client --connect tcp://127.0.0.1:1234 strftime %Y/%m/%d
```
Error at client side: 
```
connecting to "tcp://127.0.0.1:1234"
Traceback (most recent call last):
  File "/sbin/zerorpc", line 33, in <module>
    sys.exit(load_entry_point('zerorpc==0.6.3', 'console_scripts', 'zerorpc')())
  File "/usr/lib/python3.10/site-packages/zerorpc/cli.py", line 310, in main
    return run_client(args)
  File "/usr/lib/python3.10/site-packages/zerorpc/cli.py", line 270, in run_client
    if not isinstance(results, collections.Iterator):
AttributeError: module 'collections' has no attribute 'Iterator'
```

**Comment by dwarg** [comment]
On line 270, in cli.py, change the line `if not isinstance(results, collections.Iterator):` 
to 
`if not isinstance(results, collections.abc.Iterator):`

**Comment by bombela** [comment]
Some sort of backward incompatible change from the python lib? How does this change still work on older version of python :fearful:

**Comment by jackysun1982** [comment]
Hello, it seems this issue is still there? There's no way to resolve but bump the python version down?

**Comment by kratsg** [comment]
This is broken in python 3.12. The change should be based on python version (`from collections.abc import Iterator`)

**Comment by gabrielgrant** [comment]
It is surprising the Python devs would make this breaking change in a minor version bump (though I don't think Python claims to follow semver). But yea, seems accessing ABCs from the top level of the `collections` module was deprecated in v3.3 and removed in v3.10: https://docs.python.org/3.9/library/collections.html


But also... seems this should have been fixed in this repo years ago by https://github.com/0rpc/zerorpc-python/commit/c43ac74a207ecf5e8e3b38621d15a6f2ec735581 / #246  (this whole issue seems like a dupe of #231 )

@kratsg What is the error you're still seeing?

**Comment by kratsg** [comment]
> [@kratsg](https://github.com/kratsg) What is the error you're still seeing?

It's still there -- https://github.com/0rpc/zerorpc-python/blob/v0.6.3/zerorpc/cli.py#L270 . There's no new tag of zerorpc since v0.6.3 -- so I'm not sure how the fix is expected to be propagated.

**Comment by bombela** [comment]
So is the code on master handling before and after python 3.10? Shall I
merely ship a new release to pypi then?

Sorry for being a distant and distracted maintainer. I guess I have become
what I disliked about the older maintainers of my youth. yadiyada something
something old enough to see yourself becoming the vilain.

**Comment by kratsg** [comment]
I think the code on master is functional, but I've never tested it. It at least has the correct import for this particular issue.
