### ISSUE TITLE
"Bufferfull" exception

### ISSUE THREAD

**Issue by bamboosdu** [0rpc/zerorpc-python#257]
I am tring to send 5 images to server for inference.
And the exception occurs
`Traceback (most recent call last):
  File "/home/qianzhi/.conda/envs/openmmlab-xj/lib/python3.9/site-packages/zerorpc/channel.py", line 78, in _channel_dispatcher
    event = self._events.recv()
  File "/home/qianzhi/.conda/envs/openmmlab-xj/lib/python3.9/site-packages/zerorpc/events.py", line 365, in recv
    event = Event.unpack(get_pyzmq_frame_buffer(blob))
  File "/home/qianzhi/.conda/envs/openmmlab-xj/lib/python3.9/site-packages/zerorpc/events.py", line 214, in unpack
    unpacker.feed(blob)
  File "msgpack/_unpacker.pyx", line 399, in msgpack._cmsgpack.Unpacker.feed
  File "msgpack/_unpacker.pyx", line 422, in msgpack._cmsgpack.Unpacker.append_buffer
msgpack.exceptions.BufferFull
`

**Comment by bombela** [comment]
You are reaching some msgpack limits.

https://github.com/msgpack/msgpack-python
https://github.com/0rpc/zerorpc-python/blob/master/zerorpc/events.py#L214

It appears the default limit is 100MiB.
