### ISSUE TITLE
problem with 3rd example on dotcloud.com

### ISSUE THREAD

**Issue by schaefer0** [0rpc/zerorpc-python#79]
this is the example where the server defines an exception class and
the client calls the exception.

running ubuntu, client blows up with this error:

An error occurred: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zerorpc-0.4.4-py2.7.egg/zerorpc/core.py", line 148, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/usr/local/lib/python2.7/dist-packages/zerorpc-0.4.4-py2.7.egg/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/usr/local/lib/python2.7/dist-packages/zerorpc-0.4.4-py2.7.egg/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "zerorpc_server3.py", line 5, in bad
    raise Exception(":P")
Exception: :P

the server reports the error below, but does not blow up:

No handlers could be found for logger "zerorpc.core"

**Comment by bombela** [comment]
I am not sure to understand the request completely. Feel free to re-open with more details.
